# 날짜 데이터

In [104]:
import datetime
now = datetime.datetime.now()   #  현재국가 시간 (colab 미국)
print (now)

2022-10-03 01:27:56.545631

In [105]:
type(now)

datetime.datetime

## naive datetime and aware datetime
- naive datetime (timezone 정보가 없음)
- aware datetime (timezone 정보가 있음)
- 함께 계산이 안됨 (항상 aware datetime 사용 권장)

In [132]:
now_naive = datetime.datetime.utcnow()  # naive
now_naive

datetime.datetime(2022, 10, 3, 1, 37, 59, 448197)

In [133]:
from pytz import utc
now_aware = utc.localize(now_naive) # aware
now_aware

datetime.datetime(2022, 10, 3, 1, 37, 59, 448197, tzinfo=<UTC>)

In [135]:
dt_utc = datetime.datetime.utcnow()    #  UTC (Coordinated Universal Time, 영국)

KST = datetime.timezone(timedelta(hours=9))  # time zone: 한국은 UTC 와 9 시간 차이
dt_korea = dt_utc.astimezone(KST)

In [136]:
dt_utc   # naive datetime

datetime.datetime(2022, 10, 3, 1, 38, 41, 389180)

In [137]:
dt_korea   # aware datetime

datetime.datetime(2022, 10, 3, 10, 38, 41, 389180, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))

In [155]:
try:
    print(dt_korea - dt_utc)
except:
    print("Error: naive datetime과 aware datetime을 서로 섞어서 쓰지 못한다.")

Error: naive datetime과 aware datetime을 서로 섞어서 쓰지 못한다..

In [140]:
time1 = datetime.datetime(2019, 1, 1, 0, 0, 0, tzinfo=KST)  # another aware
time1

datetime.datetime(2019, 1, 1, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))

In [141]:
dt_korea - time1    # aware datetimes can be subtracted.

datetime.timedelta(days=1371, seconds=38321, microseconds=389180)

- extract detailed information

In [114]:
# 정보 추출하기
KST = datetime.timezone(timedelta(hours=9)) 
now = datetime.datetime.now()
now_kr = now.astimezone(KST)
print(now_kr)
print (now_kr.year)
print (now_kr.month)
print (now_kr.day)
print(now_kr.hour)
print(now_kr.minute)
print(now_kr.second)
print(now_kr.microsecond)
print(now_kr.weekday())      #  Monday is 0

2022-10-03 10:30:20.246579+09:00
2022
10
3
10
30
20
246579
0

In [142]:
# 날짜 정보 다듬기

KST = datetime.timezone(timedelta(hours=9)) 
now = datetime.datetime.now()
now_kr = now.astimezone(KST)
print (str(now_kr.month) + "/" + str(now_kr.day) + "/" + str(now_kr.year))

10/3/2022

In [143]:
# 시간 정보 다듬기

print (str(now_kr.hour) + ":" + str(now_kr.minute) + ":" + str(now_kr.second))

10:39:43

- time zone 확인

In [144]:
import pytz

for tz in pytz.all_timezones:
    if 'Seoul' in tz:
         print(tz)

Asia/Seoul

In [154]:
KST = pytz.timezone('Asia/Seoul')
date = datetime.datetime.now()     # local jupyter 사용시
date = date.replace(tzinfo=KST)
date

datetime.datetime(2022, 10, 3, 1, 44, 59, 6687, tzinfo=<DstTzInfo 'Asia/Seoul' LMT+8:28:00 STD>)

In [156]:
# 주의: naive datetime과 aware datetime을 서로 섞어서 쓰지 못한다.
datetime.datetime.utcnow() + datetime.datetime.now(tz=timezone.utc)

TypeError: ignored

# 영업일 캘린더 (KRX)

* 한국거래소 홈페이지에서 휴장일을 xls로 받을 수 있다
* 휴장일 데이터로 부터 개장일(market days)를 생성
* 해외 시장(CME, EUREX)등은  pandas-market-calendars를 활용

<img width="320" src="http://i.imgur.com/ClIQff8.jpg" >

#### http://fb.com/financedata , http://financedata.github.io
<!-- TEASER_END -->

In [ ]:
# you need newer version of xlrd to read 'xlxs' file
!pip install xlrd=='1.2.0'

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlrd==1.2.0
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 8.4 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-1.2.0

In [ ]:
import pandas as pd
import xlrd
pd.__version__, xlrd.__version__

('1.3.5', '1.2.0')

In [ ]:
import pandas as pd

df_hdays = pd.read_excel('https://goo.gl/JGse1n')   # 휴장일 정보
df_hdays

       일자 및 요일    요일구분          비고
0   2019-01-01  화요일             신정
1   2019-02-04  월요일             설날
2   2019-02-05  화요일             설날
3   2019-02-06  수요일             설날
4   2019-03-01  금요일            삼일절
5   2019-05-01  수요일          근로자의날
6   2019-05-06  월요일     어린이날(대체휴일)
7   2019-06-06  목요일            현충일
8   2019-08-15  목요일            광복절
9   2019-09-12  목요일             추석
10  2019-09-13  금요일             추석
11  2019-10-03  목요일            개천절
12  2019-10-09  수요일            한글날
13  2019-12-25  수요일            성탄절
14  2019-12-31  화요일          연말휴장일

날짜 데이터에 요일이 함께 들어있어 가공이 필요하다.

In [ ]:
# hdays = df_hdays['일자 및 요일'].str.extract('(\d{4}-\d{2}-\d{2})', expand=False)
hdays = df_hdays['일자 및 요일']
hdays

0     2019-01-01
1     2019-02-04
2     2019-02-05
3     2019-02-06
4     2019-03-01
5     2019-05-01
6     2019-05-06
7     2019-06-06
8     2019-08-15
9     2019-09-12
10    2019-09-13
11    2019-10-03
12    2019-10-09
13    2019-12-25
14    2019-12-31
Name: 일자 및 요일, dtype: object

In [ ]:
hdays = pd.to_datetime(hdays)    # string -> datetime type conversion
hdays.name = '날짜'
hdays                             # series

0    2019-01-01
1    2019-02-04
2    2019-02-05
3    2019-02-06
4    2019-03-01
5    2019-05-01
6    2019-05-06
7    2019-06-06
8    2019-08-15
9    2019-09-12
10   2019-09-13
11   2019-10-03
12   2019-10-09
13   2019-12-25
14   2019-12-31
Name: 날짜, dtype: datetime64[ns]

# 개장일(market day)

2019년 중에 개장일(market day)목록을 만들어 보자. 우선 pandas.date_range() 함수를 사용하여 1월 1일~ 12월 31까지 날짜를 생성한다. (365일)

In [ ]:
mdays = pd.date_range('2019-01-01', '2019-12-31')
mdays

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

이때 freq 를 'B'로 지정(business day)하면, 주말(토,일)은 제외된다. (260일)

날짜 생성에 대해서는 다음 URL을 참고 하자. 
https://pandas.pydata.org/pandas-docs/stable/timeseries.html

특히, 간격 별칭(Offset Aliases)에 대해서는 아래 표에 정리되어 있다.

https://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases

In [ ]:
mdays = pd.date_range('2019-01-01', '2019-12-31', freq='B') # business day
mdays

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-07', '2019-01-08', '2019-01-09', '2019-01-10',
               '2019-01-11', '2019-01-14',
               ...
               '2019-12-18', '2019-12-19', '2019-12-20', '2019-12-23',
               '2019-12-24', '2019-12-25', '2019-12-26', '2019-12-27',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=261, freq='B')

여기서 휴일을 제외(df.drop)하면, 모든 영업일(market day)가 만들어진다. (244일)

In [ ]:
mdays = mdays.drop(hdays)
mdays

DatetimeIndex(['2019-01-02', '2019-01-03', '2019-01-04', '2019-01-07',
               '2019-01-08', '2019-01-09', '2019-01-10', '2019-01-11',
               '2019-01-14', '2019-01-15',
               ...
               '2019-12-16', '2019-12-17', '2019-12-18', '2019-12-19',
               '2019-12-20', '2019-12-23', '2019-12-24', '2019-12-26',
               '2019-12-27', '2019-12-30'],
              dtype='datetime64[ns]', length=246, freq=None)

# DataFrame에 휴장일 적용하기

DataFrame에서 개장일(market day)만을 추출해해야 하는 경우를 살펴보자.

다음과 같은 데이터를 가정해 보자. (5월 1일\~5월 30일, 1~30까지 values로 할당)

In [ ]:
data = {'values': range(1,32)}; data

{'values': range(1, 32)}

In [ ]:
df_sample = pd.DataFrame(data, index=pd.date_range('2019-05-01', '2019-05-31'))
df_sample.head()

            values
2019-05-01       1
2019-05-02       2
2019-05-03       3
2019-05-04       4
2019-05-05       5

위 데이터 중에서 개장일만 추출하고자 한다. DateTimeIndex를 가진 두 개의 DataFrame의 교집합을 구하는 간단한 방법으로 pd.merge()을 쓸 수 있다.

In [ ]:
# 개장일을 index로 갖는 DataFrame
df_mdays = pd.DataFrame(index=mdays)
df_mdays.head()

Empty DataFrame
Columns: []
Index: [2019-01-02 00:00:00, 2019-01-03 00:00:00, 2019-01-04 00:00:00, 2019-01-07 00:00:00, 2019-01-08 00:00:00]

In [ ]:
# 두 DataFrame (df_sample, df_mdays)의 인덱스를 기준으로 합친다(merge)
df = pd.merge(df_sample, df_mdays, right_index=True, left_index=True)
            # join is done on columns or indexes
            # use the index from the left(right) df as the join key(s)
            # merging: 공통된 값을 기준으로 합치기
            # concatenate: 단순 합치기
df.head(3).append(df.tail(3))

            values
2019-05-02       2
2019-05-03       3
2019-05-07       7
2019-05-29      29
2019-05-30      30
2019-05-31      31

이 경우, 두 인덱스의 공동부분(intersection)만 남으므로 개장일만 남게 된다.

# CME, EUREX 휴장일

영업일 캘린더 메뉴에서 한국거래소(KRX)외에 CME, EUREX와 캘린더도 제공하며, 엑셀로 다운로드 한 2017년 데이터는 다음과 같다.
- Chicago Mercantile Exchange: 세계 최대 선물 거래소

* hdays-2017-CME.xls ( https://goo.gl/cvnhy2 ) 
* hdays-2017-EUREX.xls ( https://goo.gl/s2PgBx )

In [ ]:
pd.read_excel('https://goo.gl/cvnhy2')

            구분          일자 요일   시장             비고
0           휴장  2017/01/02  월  CME  New Year' Day
1           휴장  2017/04/14  금  CME    Good Friday
2  단축종료(03:15)  2017/11/24  금  CME      추수감사절 다음날
3           휴장  2017/12/25  월  CME  Christmas Day

In [ ]:
pd.read_excel('https://goo.gl/s2PgBx')

   구분          일자 요일     시장             비고
0  휴장  2017/04/14  금  EUREX    Good Friday
1  휴장  2017/04/17  월  EUREX  Easter Monday
2  휴장  2017/05/01  월  EUREX     Labour Day
3  휴장  2017/12/25  월  EUREX  Christmas Day
4  휴장  2017/12/26  화  EUREX     Boxing Day

# pandas-market-calendars
- 해외 시장의 개장일(market day)을 관리하기 위해 위 엑셀 데이터를 사용하기 보다는 pandas-market-calendars 라이브러를 권한다. http://pandas-market-calendars.readthedocs.io
- NYSE, CME, EUREX 등 시장에 대한 개장일과 개장 시간등을 관리할 수 있다.
- 2017 https://fb.com/financedata